Neighborhood.create!(:name => 'Downtown', :description => 'Close to the convention center, sparse offerings.')
Neighborhood.create!(:name => 'Federal Hill', :description => 'Easy cab ride from convention center, tons of great bars.')
Neighborhood.create!(:name => 'Inner Harbor', :description => 'Huge tourist trap.')
Neighborhood.create!(:name => 'Little Italy', :description => 'Its-a-me Mario!')
Neighborhood.create!(:name => 'Fells Point', :description => 'Beer by the water.')
Neighborhood.create!(:name => 'Canton', :description => 'Hit the hive or the bars, your choice.')